@hostname = 127.0.0.1
@port = 8001
@host = {{hostname}}:{{port}}
@contentType = application/json
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhdXRoMCIsInVzZXJOYW1lIjoiYSIsImV4cCI6MTU5MTYzMzg3MX0.bCEFWcyqfrixAxDMdkqbOVoC_QSaJAXqR9pIQ6brTdw

###
GET http://{{host}}/questionnaire/share/5ed4ad1fdcaf7f456edddb20

###
GET http://{{host}}/questionnaire/5ecf40b0a3ffcc141f89a7be
x-token: {{token}}

###
GET http://{{host}}/questionnaire/user/6?page=0&size=5
x-token: {{token}}

###
GET http://{{host}}/trash/user/6?page=0
x-token: {{token}}

###
POST http://{{host}}/questionnaire/delete
x-token: {{token}}
Content-Type: {{contentType}}

{
    "uid":6,
    "id":"5ed0ac1a71ba90311a779875"
}

###
POST http://{{host}}/questionnaire/close
x-token: {{token}}
Content-Type: {{contentType}}

{
    "uid":6,
    "id":"5ed8daa42eb6865a234c5be4"
}
###
POST http://{{host}}/questionnaire/public
x-token: {{token}}
Content-Type: {{contentType}}

{
    "uid":6,
    "id":"5ed05468686f43645f0f59fb"
}