@hostname = localhost
@port = 8001
@host = {{hostname}}:{{port}}
@contentType = application/json
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhdXRoMCIsInVzZXJOYW1lIjoiYSIsImV4cCI6MTU5MDgyMDI1NX0.2PMejWabOFBUaZjqmQ0RjrFG_XMMLEPXkQVgy7EwP3g

###
GET http://{{host}}/questionnaire/share/5ecfbdd812f78d4ad2f761f2

###
GET http://localhost:8001/questionnaire/5ecf40b0a3ffcc141f89a7be
x-token: {{token}}

###
GET http://localhost:8001/questionnaire/user/6?page=1
x-token: {{token}}

###
GET http://localhost:8001/questionnaire/user/6/trash?page=0
x-token: {{token}}

###

POST http://{{host}}/questionnaire/delete
x-token: {{token}}
Content-Type: {{contentType}}

{
    "uid":6,
    "id":"5ecfb0cd3653ea4e167e9d4c"
}
###
