@hostname = localhost
@port = 8001
@host = {{hostname}}:{{port}}
@contentType = application/json
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhdXRoMCIsInVzZXJOYW1lIjoiYSIsImV4cCI6MTU5MDgzNzIzM30.8Oy5UpWMKYlQORRAL7m_bQ2fRgCaJ9-_HRFJLm6VHSM

###
GET http://{{host}}/trash/recover/5ecfb0cd3653ea4e167e9d4c
x-token: {{token}}
###

POST http://{{host}}/trash/delete/5ed0ac1a71ba90311a779875
x-token: {{token}}
###
POST http://{{host}}/trash/clear/user/6
x-token: {{token}}