@hostname = localhost
@port = 8001
@host = {{hostname}}:{{port}}
@contentType = application/json
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhdXRoMCIsInVzZXJOYW1lIjoiYSIsImV4cCI6MTU5MTI1Nzk2Nn0.jA-DUkga9ehNVaNYvr9LBnMoMQBH1g_teObX3CFJsa4

###
POST http://{{host}}/user/login
Content-Type: {{contentType}}

{
  "userName": "a",
  "password": "123"
}

###
POST http://{{host}}/user/1/questionnaire
x-token: {{token}}
Content-Type: {{contentType}}

{
    "id":"",
    "title":"问66",
    "description":"dfdc1",
    "status":2,
    "create_time":"2020-05-28T15:56:24.525Z",
     "questions":[
        {"qtype":"多选","require":true,"qtitle":"择一下选项(多选)","options":["选项1","选项2"]},
        {"qtype":"单选","require":false,"qtitle":"请选个选项","options":["选1","选2"]},
        {"qtype":"填空","require":false,"qtitle":"标题标题","options":[]},
        {"qtype":"评分","require":true,"qtitle":"评分评分","options":[]},
        {"qtype":"下拉","require":true,"qtitle":"下拉","options":["下拉!!"]},
        {"qtype":"比重","require":true,"qtitle":"比重","options":["比重1","比重2"]}
    ]
}
###