@hostname = localhost
@port = 8001
@host = {{hostname}}:{{port}}
@contentType = application/json
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhdXRoMCIsInVzZXJOYW1lIjoiYSIsImV4cCI6MTU5MDU0NDIyMH0.0o_G7lb2OFgakl8EWSVD4VMEBz_-eH5AcllFokkOBdU

###
POST http://{{host}}/user/login
Content-Type: {{contentType}}

{
  "userName": "a",
  "password": "123"
}

###
GET http://{{host}}/user/all
x-token: {{token}}

###